name: Update OOD Portal in Kubernetes
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  update:
    runs-on: self-hosted
    steps:
      - name: Patch APPS_REF and restart OOD portal
        run: |
          kubectl set env deployment/ood-portal \
            --containers=clone-apps \
            APPS_REF=${{ github.sha }} \
            -n production
          kubectl rollout restart deployment/ood-portal -n production
          kubectl rollout status  deployment/ood-portal -n production
